### ISSUE TITLE
Building the example

### ISSUE THREAD

**Issue by ObjSal** [Zutubi/com.zutubi.diff#5]
Hello there, Thanks for sharing this!

I was able to build the main jar, but when trying to build the example following the instruction in the README it fails:

~/Downloads/com.zutubi.diff-master/examples/patch ⮀ gradle jar

FAILURE: Build failed with an exception.

* Where:
Build file '~/Downloads/com.zutubi.diff-master/examples/patch/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'patch'.
> Could not find property 'manifest' on root project 'patch'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.573 secs

Thanks!
-Sal

**Comment by jsankey** [comment]
Thanks for the report Sal, it should be fixed now.
